name: Docs generation

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    


jobs:
  tester:
    name: Test the code
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
 
     - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-toolbox

      - name: Docs
        run: |
          cd docs
          make html SPHINXOPTS="-W --keep-going"
          # The extra options are there to fail on warnings
